import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,BookOpen,ClipboardList,FlaskConical,LayoutDashboard,LockKeyhole,Menu,ScanLine} from 'lucide-react';
import {useSession} from './useSession';
import {role} from './api';
import {Button,ConnectionStatus,Toast} from './components';
import {Operator} from './Operator';
import {Participant,Stimulus} from './Participant';
import {ContentPreview,DemoPage,Monitor,Review} from './Research';
import './styles.css';
const navigation=[['/operator','Session console',LayoutDashboard],['/monitor','Live monitor',ScanLine],['/review','Review data',ClipboardList],['/content-preview','Materi eksperimen',BookOpen],['/demo','Demo model',Activity]] as const;
function App(){
 const {state:s,online,paired,error,pair}=useSession();const [pin,setPin]=useState(''),[message,setMessage]=useState(''),[menu,setMenu]=useState(false),[pairing,setPairing]=useState(false);
 if(!paired&&role==='operator')return <main className="login"><div className="brand"><span className="brand-mark">T<span>F</span></span>TraceFokus <small>v2</small></div><div className="login-form"><LockKeyhole size={28} strokeWidth={1.4}/><span className="eyebrow">RESEARCHER ACCESS</span><h1>Hubungkan konsol</h1><p>Masukkan PIN operator yang muncul di terminal laptop saat server dimulai.</p><form onSubmit={e=>{e.preventDefault();setPairing(true);void pair(pin).finally(()=>setPairing(false))}}><label htmlFor="pin">PIN operator</label><input id="pin" autoComplete="off" value={pin} onChange={e=>setPin(e.target.value)} placeholder="8 karakter dari terminal"/><Button disabled={!pin||pairing}>{pairing?'Menghubungkan…':'Hubungkan'}</Button></form>{error&&<p role="alert" className="error-text">{error}</p>}<small>Lokal · Tidak memerlukan akun cloud</small></div><div className="login-foot">OBSERVABLE BEHAVIOR RESEARCH / LOCAL WORKSPACE</div></main>;
 if(role!=='operator')return <div className="participant-shell"><header><span>Kegiatan penelitian</span><ConnectionStatus online={online}/></header>{s?.mode!=='RESEARCH'&&s&&<div className="dev-banner">{s.mode}</div>}{!s?<div className="waiting"><h1>Menghubungkan…</h1><p>{error||'Pastikan perangkat terhubung ke jaringan laptop.'}</p></div>:role==='participant'?<Participant s={s}/>:<Stimulus s={s}/>}</div>;
 return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><a href="/operator" className="brand"><span className="brand-mark">T<span>F</span></span>TraceFokus <small>v2</small></a><div className="workspace-label">RESEARCH WORKSPACE</div><nav>{navigation.map(([path,label,Icon])=><a key={path} href={path} className={(location.pathname===path||location.pathname==='/'&&path==='/operator')?'active':''}><Icon size={18}/>{label}</a>)}</nav><div className="sidebar-bottom"><FlaskConical size={20}/><strong>Local-first research</strong><p>Data tersimpan di laptop.<br/>Satu jam resmi, seluruh perangkat.</p><span>TRACEFOKUS / 2.0.0</span></div></aside><div className="main-shell"><header className="topbar"><div><button className="menu-button" aria-label="Navigasi" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><span>Workspace <span className="slash">/</span> {navigation.find(x=>x[0]===location.pathname)?.[1]||'Session console'}</span></div><ConnectionStatus online={online}/></header>{s?.mode!=='RESEARCH'&&s&&<div className="dev-banner">{s.mode} — data dipisahkan dari sesi penelitian</div>}<main className="main-content">{!s?<div className="waiting"><h1>Memuat status server…</h1></div>:location.pathname==='/monitor'?<Monitor s={s}/>:location.pathname==='/review'?<Review notify={setMessage}/>:location.pathname==='/content-preview'?<ContentPreview notify={setMessage}/>:location.pathname==='/demo'?<DemoPage s={s} notify={setMessage}/>:<Operator s={s} online={online} notify={setMessage}/>}</main><footer className="main-footer"><span>LOCAL WORKSPACE</span><span>Pengamatan perilaku · Bukan pengukuran kondisi mental</span></footer></div><Toast message={message} onClose={()=>setMessage('')}/></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
