import {useEffect,useState} from 'react';
import {ArrowRight,ClipboardCheck,LockKeyhole,RefreshCw,Video} from 'lucide-react';
import {api,emit,id} from './api';
import {BlockChip,Button,ConfirmDialog,DeviceStatus,PreFlightCheck,ProgressBar,SequenceBuilder,StatusBadge,Timer,names} from './components';
export function Operator({s,online,notify}:{s:any,online:boolean,notify:(m:string)=>void}){
 const [pid,setPid]=useState('P01'),[mode,setMode]=useState('preset'),[preset,setPreset]=useState('P01'),[presets,setPresets]=useState<Record<string,string[]>>({}),[sequence,setSequence]=useState(['A1','B1','C1','A2','B2','C2']);
 const [checks,setChecks]=useState<any>(null),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[confirm,setConfirm]=useState<string|null>(null);
 useEffect(()=>{api('/setup').then(x=>setPresets(x.presets)).catch(e=>notify(e.message))},[]);
 useEffect(()=>setChecks(null),[pid,sequence]);
 const active=['CALIBRATION','BLOCK','TRANSITION'].includes(s.state),finished=['FINISHED','ABORTED'].includes(s.state);
 async function check(){setBusy(true);try{setChecks(await api('/preflight',{participant_id:pid,sequence,sequence_id:mode==='preset'?preset:'CUSTOM'}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 async function act(action:string){setBusy(true);setConfirm(null);try{if(action==='start')await api('/start',{participant_id:pid,sequence,sequence_id:mode==='preset'?preset:'CUSTOM',command_id:id(),consent_confirmed:consent});else await api('/command',{action,command_id:id(),revision:s.revision})}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 const liveReady=online&&s.camera_ready&&s.devices?.participant&&s.devices?.stimulus;
 return <>
  <div className="page-heading"><div><span className="eyebrow">EXPERIMENT / OPERATOR</span><h1>{active?'Sesi berlangsung':finished?'Sesi ditutup':'Siapkan sesi'}</h1><p>{active?'Kontrol tahapan. Perekaman tetap berjalan saat transisi.':'Satu peserta, satu sesi. Periksa perangkat sebelum memulai.'}</p></div><StatusBadge tone={s.recording?'red':'slate'}><Video size={14}/>{s.recording?'RECORDING':'STANDBY'}</StatusBadge></div>
  {(s.fault||s.vision_error)&&<div className="notice error"><b>Perlu tindakan</b><p>{s.fault||s.vision_error}</p></div>}
  {finished&&<div className="notice"><h2>{s.integrity?.status||'NEEDS REVIEW'}</h2><p>{s.participant_id} · Data sesi sudah ditutup.</p><ul>{s.integrity?.issues?.map((x:string)=><li key={x}>{x}</li>)}</ul><a href="/review">Buka review sesi →</a></div>}
  <div className="operator-grid"><div>
   {active?<section className="panel live-panel"><div className="section-head"><span className="eyebrow">{s.participant_id} / {s.sequence_id}</span><StatusBadge tone={s.state==='TRANSITION'?'violet':s.block_code?.startsWith('A')?'green':s.block_code?.startsWith('B')?'blue':'amber'}>{s.state}</StatusBadge></div><h2>{s.state==='CALIBRATION'?'Kalibrasi personal':s.state==='TRANSITION'?'Siapkan tahap berikutnya':names[s.block_code]}</h2>{s.state==='BLOCK'&&<p>Blok {s.block_number} dari 6</p>}<Timer remaining={s.remaining}/><ProgressBar value={s.duration?100*(1-s.remaining/s.duration):0}/>
    {s.state==='TRANSITION'&&<div className="next-block"><span className="eyebrow">BERIKUTNYA</span><h3>{s.next_block?<><BlockChip code={s.next_block}/> {names[s.next_block]}</>:'Seluruh blok selesai'}</h3><p>{s.next_block==='B1'||s.next_block==='B2'?'Siapkan kertas dan alat tulis. Pastikan perangkat stimulus terlihat.':s.next_block==='C2'?'Peneliti berada 30–45° di samping peserta. Gunakan prompt netral.':s.next_block==='C1'?'Pastikan perangkat stimulus dipegang peserta.':s.next_block?'Pastikan peserta siap mengikuti tugas berikutnya.':'Tekan STOP untuk menutup video dan memeriksa integritas data.'}</p><Button disabled={busy||!online||(Boolean(s.next_block)&&(!s.camera_ready||!s.devices.participant||!s.devices.stimulus))} onClick={()=>s.next_block?void act('next'):setConfirm('stop')}>{s.next_block?'Mulai blok berikutnya':'STOP SESSION'}<ArrowRight size={17}/></Button></div>}
    {s.block_code==='C2'&&<div className="prompt"><span className="eyebrow">PROMPT {s.prompt_index+1} / {s.prompts.length}</span><h3>{s.prompts[s.prompt_index]}</h3><Button variant="secondary" disabled={busy||s.prompt_index>=s.prompts.length-1} onClick={()=>{setBusy(true);emit('next_prompt').catch(e=>notify(e.message)).finally(()=>setBusy(false))}}>Prompt berikutnya <ArrowRight size={16}/></Button></div>}
    <div className="actions spread"><small><LockKeyhole size={14}/> Urutan dikunci</small><Button variant="quiet-danger" disabled={busy||!online} onClick={()=>setConfirm('abort')}>Abort sesi</Button></div>
   </section>:<section className="panel"><div className="section-head"><h2>01 <span>Identitas & urutan</span></h2><LockKeyhole size={17}/></div><label htmlFor="participant-id">ID peserta anonim</label><input id="participant-id" value={pid} maxLength={24} onChange={e=>setPid(e.target.value.toUpperCase())} placeholder="P01"/><small className="help">Tanpa nama, NIM, atau identitas pribadi.</small><div className="segmented"><button aria-pressed={mode==='preset'} onClick={()=>{setMode('preset');if(presets[preset])setSequence(presets[preset])}}>Preset</button><button aria-pressed={mode==='custom'} onClick={()=>setMode('custom')}>Urutan kustom</button></div>{mode==='preset'&&<><label htmlFor="preset">Counterbalancing preset</label><select id="preset" value={preset} onChange={e=>{setPreset(e.target.value);setSequence(presets[e.target.value])}}>{Object.keys(presets).map(p=><option key={p}>{p}</option>)}</select></>}<div className="list-heading"><b>Urutan enam blok</b><small>{s.mode==='RESEARCH'?'6 × 120 detik':'6 × 10 detik · DEV'}</small></div><SequenceBuilder value={sequence} onChange={v=>{setSequence(v);setMode('custom')}} locked={mode==='preset'}/></section>}
   {active&&<section className="panel"><div className="section-head"><h2>Urutan sesi</h2><small>Kalibrasi → 6 blok → selesai</small></div><div className="block-track">{s.sequence.map((c:string,i:number)=><div className={s.block_code===c?'current':''} key={c}><BlockChip code={c}/><small>{i+1}</small></div>)}</div></section>}
  </div><div>
   <section className="panel"><div className="section-head"><h2>{active?'Perangkat':'02'} <span>{!active&&'Kesiapan perangkat'}</span></h2><RadioIcon/></div><DeviceStatus name="Kamera laptop" ready={s.camera_ready}/><DeviceStatus name="Layar peserta" ready={s.devices?.participant}/><DeviceStatus name="Perangkat stimulus" ready={s.devices?.stimulus}/><div className="fine-rule"/><p className="muted">Buka halaman sesuai peran pada perangkat yang terhubung ke Wi-Fi yang sama.</p><div className="route-links"><a href="/participant" target="_blank" rel="noreferrer">/participant ↗</a><a href="/stimulus" target="_blank" rel="noreferrer">/stimulus ↗</a></div></section>
   {!active&&<section className="panel"><div className="section-head"><h2>03 <span>Pre-flight</span></h2><ClipboardCheck size={18}/></div><p>Periksa materi, kamera, penulis video, database, dan koneksi perangkat.</p><Button variant="secondary" onClick={()=>void check()} disabled={busy||!online}><RefreshCw size={16}/>{busy?'Memeriksa…':'Jalankan pemeriksaan'}</Button>{checks&&<PreFlightCheck checks={checks.checks}/>}<label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Peserta sudah memberikan persetujuan, memahami perekaman, dan siap memulai.</span></label><Button className="button primary full" disabled={!checks?.ok||!consent||busy||!liveReady} onClick={()=>void act('start')}>START SESSION <ArrowRight size={18}/></Button><small className="help">Kalibrasi dimulai segera. Video direkam hingga STOP.</small></section>}
   {active&&<section className="panel"><span className="eyebrow">PENYIMPANAN LOKAL</span><div className="stats"><div><b>{s.fps}</b><small>FPS kamera</small></div><div><b>{s.feature_rows}</b><small>Baris fitur</small></div></div><p className="muted">Transisi tetap terekam dan dikecualikan dari target pelatihan.</p></section>}
  </div></div>
  {confirm&&<ConfirmDialog title={confirm==='abort'?'Abort sesi ini?':'Tutup sesi dan rekaman?'} onCancel={()=>setConfirm(null)} onConfirm={()=>void act(confirm)}>{confirm==='abort'?'Video dan data yang tersedia akan dipertahankan. Sesi ditandai ABORTED dan ID ini tidak bisa ditimpa.':'Enam blok telah selesai. Server akan menutup berkas dan menjalankan pemeriksaan integritas.'}</ConfirmDialog>}
 </>
}
function RadioIcon(){return <span className="tiny-grid">▦</span>}
